CREATE TABLE IF NOT EXISTS units (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  color TEXT NOT NULL DEFAULT '#e6533f',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS words (
  id TEXT PRIMARY KEY,
  unit_id TEXT NOT NULL REFERENCES units(id) ON DELETE CASCADE,
  term TEXT NOT NULL,
  reading TEXT NOT NULL DEFAULT '',
  meaning TEXT NOT NULL DEFAULT '',
  part_of_speech TEXT NOT NULL DEFAULT '',
  example TEXT NOT NULL DEFAULT '',
  example_reading TEXT NOT NULL DEFAULT '',
  translation TEXT NOT NULL DEFAULT '',
  mastered BOOLEAN NOT NULL DEFAULT FALSE,
  starred BOOLEAN NOT NULL DEFAULT FALSE,
  review_stage INTEGER CHECK (review_stage IS NULL OR review_stage BETWEEN 0 AND 5),
  last_reviewed_at TIMESTAMPTZ,
  next_review_at TIMESTAMPTZ,
  listening_wrong INTEGER NOT NULL DEFAULT 0,
  meaning_wrong INTEGER NOT NULL DEFAULT 0,
  listening_correct INTEGER NOT NULL DEFAULT 0,
  meaning_correct INTEGER NOT NULL DEFAULT 0,
  wrong_book BOOLEAN NOT NULL DEFAULT FALSE,
  dictation_misses INTEGER NOT NULL DEFAULT 0,
  error_reviewed BOOLEAN NOT NULL DEFAULT FALSE,
  romaji TEXT NOT NULL DEFAULT '',
  pronunciation_note TEXT NOT NULL DEFAULT '',
  memory_tip TEXT NOT NULL DEFAULT '',
  synonyms TEXT NOT NULL DEFAULT '',
  similar_words TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS words_unit_order_idx ON words(unit_id, sort_order);
CREATE INDEX IF NOT EXISTS words_review_due_idx ON words(next_review_at) WHERE next_review_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS words_starred_idx ON words(starred) WHERE starred = TRUE;

ALTER TABLE words ADD COLUMN IF NOT EXISTS listening_wrong INTEGER NOT NULL DEFAULT 0;
ALTER TABLE words ADD COLUMN IF NOT EXISTS meaning_wrong INTEGER NOT NULL DEFAULT 0;
ALTER TABLE words ADD COLUMN IF NOT EXISTS listening_correct INTEGER NOT NULL DEFAULT 0;
ALTER TABLE words ADD COLUMN IF NOT EXISTS meaning_correct INTEGER NOT NULL DEFAULT 0;
ALTER TABLE words ADD COLUMN IF NOT EXISTS wrong_book BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE words ADD COLUMN IF NOT EXISTS dictation_misses INTEGER NOT NULL DEFAULT 0;
ALTER TABLE words ADD COLUMN IF NOT EXISTS error_reviewed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE words ADD COLUMN IF NOT EXISTS romaji TEXT NOT NULL DEFAULT '';
ALTER TABLE words ADD COLUMN IF NOT EXISTS pronunciation_note TEXT NOT NULL DEFAULT '';
ALTER TABLE words ADD COLUMN IF NOT EXISTS memory_tip TEXT NOT NULL DEFAULT '';
ALTER TABLE words ADD COLUMN IF NOT EXISTS synonyms TEXT NOT NULL DEFAULT '';
ALTER TABLE words ADD COLUMN IF NOT EXISTS similar_words TEXT NOT NULL DEFAULT '';
ALTER TABLE words ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS words_wrong_book_idx ON words(wrong_book) WHERE wrong_book = TRUE;

CREATE TABLE IF NOT EXISTS app_settings (
  id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  avatar TEXT NOT NULL DEFAULT 'ゆ',
  voice_gender TEXT NOT NULL DEFAULT 'female' CHECK (voice_gender IN ('female', 'male')),
  theme TEXT NOT NULL DEFAULT 'matcha' CHECK (theme IN ('matcha', 'aka', 'ai')),
  display_name TEXT NOT NULL DEFAULT '小林同学',
  streak_days INTEGER NOT NULL DEFAULT 0,
  last_study_date TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS theme TEXT NOT NULL DEFAULT 'matcha';
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS display_name TEXT NOT NULL DEFAULT '小林同学';
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS streak_days INTEGER NOT NULL DEFAULT 0;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS last_study_date TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS passages (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  source_text TEXT NOT NULL DEFAULT '',
  analysis JSONB NOT NULL DEFAULT '{"sentences":[]}',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO app_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;
